# Generated by Django 4.2.5 on 2023-09-23 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=10)),
                ('course_name', models.CharField(help_text='Name of the course', max_length=200)),
                ('credit_hours', models.IntegerField(help_text='Number of credit hours')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='Semester enrolled', max_length=10)),
                ('year', models.IntegerField(help_text='Year enrolled')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.course')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_of', models.CharField(help_text='The College where the faculty is under', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(help_text='Your Major of Study', max_length=200)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="The Student's first name", max_length=200)),
                ('last_name', models.CharField(help_text="The Student's last name", max_length=200)),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('enrollment', models.ManyToManyField(through='degree_checklist.Course_Enrollment', to='degree_checklist.course')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.major')),
            ],
        ),
        migrations.AddField(
            model_name='course_enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.faculty'),
        ),
    ]
